TOPDIR = ../../.
include $(TOPDIR)/Make/makedefs 

C++FILES =\
	ThreadObserver.c++ \
	ThreadReporter.c++ \
	SimpleThreader.c++ \
	$(NULL)

INC      += -I$(TOPDIR)/include
LIBS     += -lOpenThreadPThread

EXEC = SimpleThreader

include $(TOPDIR)/Make/makerules