# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# _OPENTHREADS_ATOMIC_USE_GCC_BUILTINS_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set _OPENTHREADS_ATOMIC_USE_GCC_BUILTINS_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The _OPENTHREADS_ATOMIC_USE_GCC_BUILTINS_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/bas/coolstream/cst-private-apollo-sdk/open_source_archive/linux/build/uclibc_4.5.2/openthreads-cst/CMakeFiles/CMakeTmp/src.cxx
# Executable    : /home/bas/coolstream/cst-private-apollo-sdk/open_source_archive/linux/build/uclibc_4.5.2/openthreads-cst/CMakeFiles/cmTryCompileExec-_OPENTHREADS_ATOMIC_USE_GCC_BUILTINS_EXITCODE
# Run arguments : 
#    Called from: [2]	/home/bas/coolstream/cst-private-apollo-sdk/open_source_archive/linux/build/uclibc_4.5.2/openthreads-cst/CMakeModules/CheckAtomicOps.cmake
#                 [1]	/home/bas/coolstream/cst-private-apollo-sdk/open_source_archive/linux/build/uclibc_4.5.2/openthreads-cst/src/OpenThreads/CMakeLists.txt

SET( _OPENTHREADS_ATOMIC_USE_GCC_BUILTINS_EXITCODE 
     0
     CACHE INT 0 FORCE)

